cmake_minimum_required(VERSION 3.21)
set (CMAKE_CXX_STANDARD 17)
list(APPEND CMAKE_PREFIX_PATH /oscar/data/gk/kshukla1/CFD_NEKRS/nekRS/3rd_party/libtorch)
find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--no-as-needed")
target_link_libraries(udf PRIVATE "${TORCH_LIBRARIES}")
